### ISSUE TITLE
Access token is broken 

### ISSUE THREAD

**Issue by fsnaix** [JuiceFV/tinder_bot#2]
after changing my password for the n-th times the code can't retrieve the access token

**Comment by JuiceFV** [comment]
Yep, I was encountering this issue. Try to login in the tinder manually via yours new fb data.

**Comment by fsnaix** [comment]
how ?

**Comment by JuiceFV** [comment]
Follow to the [Tinder](https://tinder.com), click **log in** button, and log in via facebook

**Comment by fsnaix** [comment]
Yeah and get the tinder auth id? pasted it back to the config file or the main code ?

**Comment by JuiceFV** [comment]
Nope, the problem is sneaking in the facebook. When you auths a bunch of time facebook switches the X-Auth for the tinder. Has your manual auth been successful?

**Comment by fsnaix** [comment]
Hmm, can you give it a more detailed explanation?

**Comment by fsnaix** [comment]
![Untitled](https://user-images.githubusercontent.com/51787675/115989410-6dea4f00-a5e8-11eb-8c1b-b16c4edc4ec3.png)
I got this after trying to reconfigure it agian

**Comment by JuiceFV** [comment]
Try to emquote ("") your fb email and password, for example:
```yaml
session:
    facebook_id: <your-fb-id>
    facebook_email: "<your-email>@gmail.com"
    facebook_password: "<your-pass>"
```

**Comment by JuiceFV** [comment]
In the picture above I note the braces (`<` `>`), are they parts of your login data? if not, cut them off. Probably PyYaml handles them as "special" case, what turn the data into `None`.

**Comment by fsnaix** [comment]
I still get the access token could not be retrieved. Check your username and password.
Official error: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

**Comment by JuiceFV** [comment]
1. Try to login manually. I.e. Follow tinder.com, click login via facebook, paste your email and password data.
2. If you got access to your tinder account - seems weird . Let me know.
3. In case you failed - try to commit required steps (which facebook recommends) to reclaim the access.

**Note**: use the exact same login and pass as in your yaml file. Ex:
```yaml
session:
    facebook_id: <your-fb-id>
    facebook_email: "asdasfdsdsfd@gmail.com"
    facebook_password: "<fs-0-=clnafj>"
```
Then your pass email and pass are:
* **email**  - asdasfdsdsfd@gmail.com
* **pass** - <fs-0-=clnafj>
